const menus = {
  oneApac: {
    home: 'Home',
    agendaAndMaps: 'Agenda & Maps',
    agenda: 'Agenda & Maps > Agenda',
    agendaDayOne: 'Agenda & Maps > Agenda > Day 1',
    agendaDayOnePartOne: 'Agenda & Maps > Agenda > Day 1 > Part 1',
    agendaDayOnePartTwo: 'Agenda & Maps > Agenda > Day 1 > Part 2',
    agendaDayOnePartThree: 'Agenda & Maps > Agenda > Day 1 > Part 3',
    agendaDayTwo: 'Agenda & Maps > Agenda > Day 2',
    agendaDayTwoFull: 'Agenda & Maps > Agenda > Day 2 > Full Day Agenda',
    agendaDayTwoFullPartOne: 'Agenda & Maps > Agenda > Day 2 > Full Day Agenda > Part 1',
    agendaDayTwoFullPartTwo: 'Agenda & Maps > Agenda > Day 2 > Full Day Agenda > Part 2',
    agendaDayTwoBreakout: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions',
    agendaDayTwoBreakoutPartOne: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L',
    agendaDayTwoBreakoutPartOneDetailsOne: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L > Brand Safety',
    agendaDayTwoBreakoutPartOneDetailsTwo: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L > Conversational Commerce',
    agendaDayTwoBreakoutPartOneDetailsThree: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L > Liquidity & Optimization',
    agendaDayTwoBreakoutPartOneDetailsFour: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L > Future of Signals',
    agendaDayTwoBreakoutPartOneDetailsFive: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L > #GoGlobal',
    agendaDayTwoBreakoutPartOneDetailsSix: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > A ~ L > Influencer Marketing',
    agendaDayTwoBreakoutPartTwo: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > M ~ Z',
    agendaDayTwoBreakoutPartTwoDetailsOne: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > M ~ Z > In-Stream & Watch',
    agendaDayTwoBreakoutPartTwoDetailsTwo: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > M ~ Z > Stories Creative',
    agendaDayTwoBreakoutPartTwoDetailsThree: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > M ~ Z > O2O',
    agendaDayTwoBreakoutPartTwoDetailsFour: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > M ~ Z > SBG',
    agendaDayTwoBreakoutPartTwoDetailsFive: 'Agenda & Maps > Agenda > Day 2 > Breakout Sessions > M ~ Z > Thumbstoppers',
    agendaDayTwoTraining: 'Agenda & Maps > Agenda > Day 2 > Training Sessions',
    agendaDayTwoTrainingDetailOne: 'Agenda & Maps > Agenda > Day 2 > Training Sessions > Always Do the Right Thing',
    agendaDayTwoTrainingDetailTwo: 'Agenda & Maps > Agenda > Day 2 > Training Sessions > Handling Hard Topics',
    agendaDayTwoTrainingDetailThree: 'Agenda & Maps > Agenda > Day 2 > Training Sessions > Living Your Values',
    agendaDayTwoTrainingDetailFour: 'Agenda & Maps > Agenda > Day 2 > Training Sessions > Fit & Mentally Strong',
    agendaDayTwoTrainingDetailFive: 'Agenda & Maps > Agenda > Day 2 > Training Sessions > XFN Collaboration',
    agendaDinnerEvents: 'Agenda & Maps > Agenda > Dinner Events',
    agendaDinnerEventsArtScience: 'Agenda & Maps > Agenda > Dinner Events > ArtScience Museum',
    agendaDinnerEventsMarquee: 'Agenda & Maps > Agenda > Dinner Events > Marquee',
    experience: 'Agenda & Maps > Experience Showcase',
    experienceBusiness: 'Agenda & Maps > Experience Showcase > Business',
    experienceCommunity: 'Agenda & Maps > Experience Showcase > Community',
    experiencePeople: 'Agenda & Maps > Experience Showcase > People',
    maps: 'Agenda & Maps > Venue Maps',
    mapsBreakout: 'Agenda & Maps > Venue Maps > Breakout Rooms',
    transportAndContacts: 'Transport & Contacts',
    transportAndContactsTransportation: 'Transport & Contacts > Transportation',
    transportAndContactsTransportationMBS: 'Transport & Contacts > Transportation > Marina Bay Sands',
    transportAndContactsContacts: 'Transport & Contacts > Key Contacts',
    lipSyncBattle: 'Lip Sync Battle',
    lipSyncBattleVote: 'Lip Sync Battle > Vote Confirmation > ' // appends region
  }
};

module.exports = menus;